server:
  port: 7002
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: www.eurakserver02.com
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://www.eurakserver01.com:7001/eureka/