server:
  port: 7001
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: www.eurakserver01.com
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://www.eurakserver02.com:7002/eureka/